spring.application.name=backend

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/onecare
spring.datasource.username=[your username]
spring.datasource.password=[your password]
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SQL Init
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.mode=always

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=auto
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
